

### register
POST http://localhost:5000/api/v1/auth/signup
Content-Type: application/json

{
    "fullname": "mike test2",
    "email": "miketest@121223.com",
    "password": "iamthatguymike2",
    "confirmPassword": "iamthatguymike2",
    "role": "Agent"
}

### login
POST http://localhost:5000/api/v1/auth/signin
Content-Type: application/json

{
     "email": "omwami@rules.com",
    "password": "12345678yh"
}