module.exports = {
    department: "department",
    // sla: "sla",
    severity: "severity",
    status: "status",
    role: "role",
    user: "user",
    auth: "auth",
    role_user: "role_user",
    ticket_type: "ticket_type",
    ticket_subtype: "ticket_subtype",
    ticket: "ticket",
    ticket_history: "ticket_history",
    resolution: "resolution",
};
